//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework_0001
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpFamily
    {
        public int Id { get; set; }
        public string Married { get; set; }
        public string Address1 { get; set; }
        public System.DateTime Birthdate { get; set; }
    }
}
